@testitem "Aqua quality assurance" begin
    using Aqua
    using Aquarium

    # Every dependency and weak dependency must carry an upper-bounded compat entry.
    # This is a hard requirement for General's AutoMerge, so it is asserted rather
    # than assumed.
    Aqua.test_deps_compat(Aquarium)

    # No dependency may be declared and never loaded. This is what caught QuadGK,
    # which the library replaced with its own Gauss-Legendre rule while the
    # @testitem blocks kept quadgk as a ground-truth reference.
    Aqua.test_stale_deps(Aquarium)

    # Every exported name must resolve. Worth asserting precisely because the export
    # surface is generated by @exportAll rather than written by hand.
    Aqua.test_undefined_exports(Aquarium)

    # Method signatures must not carry unbound type parameters.
    Aqua.test_unbound_args(Aquarium)

    # Aqua.test_ambiguities and Aqua.test_piracies are deliberately not enabled here.
    # Both are properties of the export surface and the type hierarchy, which are
    # slated for curation in the next release series (see docs/adr/0001). Enabling
    # them now would either fail for reasons this phase has explicitly deferred, or
    # invite fixes that pre-empt that decision.
end
